using System.Globalization;

namespace OmniKeyVault.Application;

/// <summary>English (en-US) localizer. Every key in <see cref="ZhCnLocalizer"/>
/// has a counterpart here so the GUI can be fully re-rendered in English
/// without code changes. New keys added to the Chinese file must also be
/// added here (the test suite enforces parity).</summary>
public sealed class EnUsLocalizer : IStringLocalizer
{
    public string Locale => Locales.EnUs;

    public string Get(string key) => key switch
    {
        // === Common ===
        "common.save" => "Save",
        "common.cancel" => "Cancel",
        "common.close" => "Close",
        "common.delete" => "Delete",
        "common.confirm" => "Confirm",
        "common.back" => "Back",
        "common.search" => "Search",
        "common.refresh" => "Refresh",
        "common.yes" => "Yes",
        "common.no" => "No",
        "common.ok" => "OK",
        "common.retry" => "Retry",
        "common.import" => "Import",
        "common.export" => "Export",
        "common.rotate" => "Rotate",
        "common.download" => "Download",
        "common.upload" => "Upload",
        "common.attach" => "Attach",
        "common.attachments" => "Attachments",

        // === Unlock window ===
        "unlock.title" => "OmniKey Vault",
        "unlock.master_password" => "Master password",
        "unlock.unlock_button" => "Unlock vault",
        "unlock.use_recovery_key" => "Use recovery key",
        "unlock.create_vault" => "No vault? Create one",
        "unlock.remember_15m" => "Keep unlocked for 15 minutes",
        "unlock.invalid_password" => "Invalid credentials, try again",
        "unlock.empty_password" => "Please enter the master password",
        "unlock.deriving_key" => "Deriving key…",
        "unlock.vault_not_found" => "Vault file not found",
        "unlock.last_access" => "Last access",
        "unlock.browse" => "📂 Browse",
        "unlock.tagline" => "Local-first · End-to-end encrypted",
        "unlock.footer" => "No cloud recovery · Zero-knowledge",

        // === Main window ===
        "main.search_watermark" => "Search entries, fields, tags…",
        "main.list_title_all" => "All entries",
        "main.list_title_uncategorized" => "Uncategorized",
        "main.empty_title" => "No matching entries",
        "main.empty_sub" => "Try clearing filters or changing the search keyword.",
        "main.empty_vault" => "Vault is empty",
        "main.empty_vault_sub" => "Click + New entry to start",
        "main.locked" => "Vault is locked",
        "main.locked_sub" => "Run `okv vault unlock` to unlock the vault",
        "main.detail_empty" => "Select an entry",
        "main.detail_subtitle" => "Pick an entry from the list to see its details.",
        "main.folder_section" => "Folders",
        "main.tags_section" => "Tags",
        "main.new_entry" => "+ New entry",
        "main.import" => "↓ Import",
        "main.export" => "↑ Export",
        "main.sort" => "⇅ Sort",
        "main.copy_main" => "⧉  Copy main field",
        "main.copy_all" => "📋  Copy all fields (JSON)",
        "main.edit" => "✎  Edit",
        "main.duplicate" => "⧉  Duplicate",
        "main.history" => "🕐  History",
        "main.delete" => "🗑  Delete",
        "main.copied" => "Copied · will clear in 8 seconds",
        "main.clipboard_cleared" => "Clipboard cleared",
        "main.vault_unlocked_with_count" => "Vault unlocked · {0} entries loaded",
        "main.vault_unlocked" => "Vault unlocked",
        "main.vault_locked" => "Vault locked · memory cleared",
        "main.switched_profile" => "Switched to {0} profile",
        "main.sync_synced" => "Synced · this device",
        "main.sync_manual" => "Syncing… (manual)",
        "main.sync_complete" => "Sync complete",
        "main.sync_no_change" => "Already up to date",
        "main.sync_took_remote" => "Pulled updates from remote",
        "main.sync_local_ahead" => "Local version is ahead (copy vault to sync dir)",
        "main.sync_merged" => "Merged {0} entries",
        "main.sync_failed" => "Sync failed:",
        "main.sync_select_dir" => "Select sync directory (should contain another .okv file, e.g. cloud drive path)",
        "main.sync_no_okv_in_dir" => "No .okv file in {0}",
        "main.sync_remote_change_detected" => "{0} changed · click Sync to view latest",
        "main.remote_change_banner" => "Remote has updates",
        "main.dev_tools" => "Dev Tools · v0.2",
        "main.export_seed" => "📤 Export Seed",
        "main.import_seed" => "📥 Import Seed",
        "main.sync" => "🔄 Sync",
        "main.never_synced" => "Never synced",
        "main.lock_countdown_fmt" => "Unlocked · {0} min left",
        "main.profile_banner_dev" => "DEV — non-production data",
        "main.profile_banner_test" => "TEST — test data",
        "main.import_kdbx" => "🔐 Import KeePass",
        "main.import_bitwarden" => "📥 Import Bitwarden",
        "main.search_advanced" => "🔍 Advanced search",
        "main.search_hint" => "Supports tags:dev / platform:openai / field:api_key:sk-* syntax",

        // === Editor ===
        "editor.title_new" => "New entry",
        "editor.title_edit" => "Edit entry",
        "editor.name" => "Name",
        "editor.name_hint" => "e.g. OpenAI production",
        "editor.template" => "Platform (template)",
        "editor.platform_id" => "Platform ID (independent)",
        "editor.platform_id_hint" => "e.g. openai / github (independent of template)",
        "editor.type" => "Type",
        "editor.folder" => "Folder",
        "editor.expires" => "Expires (optional)",
        "editor.tags" => "Tags (comma-separated)",
        "editor.tags_hint" => "ai, work, prod",
        "editor.fields" => "Fields",
        "editor.add_totp" => "🔐 Add TOTP",
        "editor.add_file_ref" => "📎 Add attachment",
        "editor.add_field" => "+ Add field",
        "editor.field_key_hint" => "Field name",
        "editor.field_value_hint" => "Value",
        "editor.notes" => "Notes",
        "editor.duplicate_totp" => "totp_uri field already exists",
        "editor.name_required" => "Please enter an entry name",
        "editor.vault_locked" => "Vault is locked",
        "editor.save_failed" => "Save failed:",
        "editor.rotate" => "🔄 Rotate key",
        "editor.rotate_title" => "Rotate key",
        "editor.rotate_confirm" => "Confirm rotating {1} on {0}? Old value will be archived to history.",
        "editor.rotate_success" => "✓ Rotated {0}",
        "editor.rotate_failed" => "✕ Rotation failed:",
        "editor.rotate_unsupported" => "This entry's platform does not support one-click rotation",
        "editor.rotate_in_progress" => "Calling platform API…",

        // === Settings ===
        "settings.title" => "Settings",
        "settings.general" => "General",
        "settings.security" => "Security",
        "settings.sync" => "Sync",
        "settings.profiles" => "Profiles",
        "settings.devices" => "Devices",
        "settings.danger" => "Danger zone",
        "settings.about" => "About",
        "settings.language" => "Language",
        "settings.theme" => "Theme",
        "settings.theme_system" => "System",
        "settings.theme_dark" => "Dark",
        "settings.theme_light" => "Light",
        "settings.auto_lock" => "Auto-lock (idle)",
        "settings.clipboard" => "Clipboard auto-clear",
        "settings.lock_on_session" => "Lock immediately on session lock",
        "settings.lock_on_suspend" => "Lock immediately on system suspend",
        "settings.idle_minutes" => "Idle timeout (minutes)",
        "settings.sync_dir" => "Sync directory",
        "settings.sync_dir_hint" => "(leave empty to watch vault's parent directory)",
        "settings.watcher_enabled" => "Enable file watcher (auto-prompt on .okv change)",
        "settings.change_password" => "Change master password",
        "settings.view_recovery" => "View recovery key",
        "settings.view_recovery_hint" => "View recovery key: use CLI: okv vault info",
        "settings.language_changed" => "✓ Language switched to {0}",
        "settings.theme_changed" => "✓ Theme switched to {0} (takes effect after window reopen)",
        "settings.watcher_changed" => "✓ File watcher {0} · takes effect on next unlock",
        "settings.sync_dir_set" => "✓ Sync directory set",
        "settings.device_revoked" => "✓ Device {0} revoked",
        "settings.device_revoke_failed" => "✕ Revoke failed:",
        "settings.attachment_dir" => "Attachment storage directory",
        "settings.attachment_dir_hint" => "(leave empty for default %APPDATA%/OmniKeyVault/attachments/)",

        // === Profile switcher ===
        "profile.switcher_title" => "Switch profile",
        "profile.new" => "+ New profile",
        "profile.delete_confirm" => "Profile \"{0}\" contains {1} entries. Delete?",
        "profile.delete_failed" => "Delete failed:",
        "profile.create_failed" => "Create failed:",
        "profile.name_required" => "Name must be 1-32 characters",
        "profile.name_exists" => "Profile \"{0}\" already exists",
        "profile.name_hint" => "e.g. staging / sandbox / team-a",
        "profile.color" => "Color",
        "profile.create" => "Create",
        "profile.local_only" => "Local only",
        "profile.synced" => "Synced",
        "profile.count_fmt" => "{0} entries",

        // === Seed export/import ===
        "seed.export_title" => "Export Seed (.okv.dev)",
        "seed.export_hint" => "Seed files are not protected by the master password — they contain only profile metadata + field schema, suitable for team / cross-device schema sync. Secret fields can be stripped.",
        "seed.export_profile" => "Profile",
        "seed.export_path" => "Export path",
        "seed.export_default" => "📂 Default location",
        "seed.export_strip" => "Strip secret fields (recommended · safe to share)",
        "seed.export_strip_hint" => "✓ Strip mode: seed contains no secret fields, safe to share schema and non-sensitive fields with the team.",
        "seed.export_full_hint" => "Full export: includes secret fields. Use only in controlled environments, never share publicly.",
        "seed.export_button" => "Export",
        "seed.import_title" => "Import Seed (.okv.dev)",
        "seed.import_hint" => "Import entries from a .okv.dev file. Production isolation: only allowed into dev/test profiles. Importing to prod requires a confirmation phrase.",
        "seed.import_path" => "Seed file path",
        "seed.import_recent" => "📂 Find latest",
        "seed.import_target" => "Target profile",
        "seed.import_prod_confirm" => "⚠ Importing to prod is dangerous. Type \"IMPORT TO PROD\" to confirm:",
        "seed.import_prod_required" => "Importing to prod requires typing \"IMPORT TO PROD\" to prevent accidental pollution of production data.",
        "seed.import_button" => "Import",
        "seed.import_new_profile" => "+ New profile",

        // === KeePass import (v0.3 S5-T6) ===
        "keepass.import_title" => "Import from KeePass",
        "keepass.import_hint" => "Supports KeePass 2.x XML export format (in KeePass: File → Export → KeePass 2 XML).",
        "keepass.import_path" => "XML file path",
        "keepass.import_button" => "Import to current profile",
        "keepass.import_success_fmt" => "✓ Imported {0} entries to {1}",
        "keepass.import_failed" => "✕ KeePass import failed:",
        "keepass.parse_error" => "Could not parse KeePass XML. Please confirm it is a KeePass 2.x export.",

        // === Search window (v0.3 S6-T3) ===
        "search.title" => "Advanced search",
        "search.placeholder" => "tags:dev AND platform:openai",
        "search.syntax_help" => "Supports tags: / platform: / field:KEY:VALUE / expired / free text · combine with AND / OR",
        "search.results_fmt" => "{0} match(es)",
        "search.no_results" => "No matching entries",
        "search.clear" => "Clear",
        "search.field_highlighted" => "matched field",

        // === Attachments (v0.3 S6-T5) ===
        "attachment.upload" => "📎 Upload attachment",
        "attachment.download" => "⬇ Download",
        "attachment.replace" => "🔄 Replace",
        "attachment.delete" => "🗑 Delete",
        "attachment.size_fmt" => "{0} · {1}",
        "attachment.confirm_delete" => "Delete attachment \"{0}\"?",
        "attachment.upload_failed" => "Upload failed:",
        "attachment.not_found" => "Attachment missing or deleted",
        "attachment.kind" => "Attachment",
        "attachment.uploaded" => "✓ Uploaded {0} ({1})",

        // === Sync conflict resolver ===
        "sync.conflict_title" => "⚠ Sync conflict",
        "sync.conflict_summary_fmt" => "{0} conflicting entries detected (vector clock cannot auto-merge)",
        "sync.conflict_local_vector" => "Vector clock state",
        "sync.conflict_choice" => "Choose resolution:",
        "sync.conflict_keep_local" => "💾 Keep local",
        "sync.conflict_keep_local_sub" => "Overwrite remote with local. Other devices' changes will be lost.",
        "sync.conflict_take_remote" => "📥 Take remote",
        "sync.conflict_take_remote_sub" => "Overwrite local with remote. Local changes will be lost.",
        "sync.conflict_merge" => "🔀 Auto-merge",
        "sync.conflict_merge_sub" => "Merge non-conflicting entries; conflicting fields require manual follow-up.",
        "sync.conflict_cancel" => "Cancel",
        "sync.conflict_local_kept" => "Local version kept (default local-wins)",

        // === Device trust ===
        "trust.title" => "🔐 Trust new device",
        "trust.body" => "Detected a signature from an unrecognized device. Devices use Ed25519 public keys to sign vault files. Once trusted, all future signatures from this device will pass verification automatically.",
        "trust.device_id" => "Device ID",
        "trust.public_key" => "Public key fingerprint",
        "trust.reason" => "Trigger reason",
        "trust.choice" => "Choose:",
        "trust.trust" => "✓ Trust and remember this device",
        "trust.trust_once" => "✓ Trust once (not persisted)",
        "trust.reject" => "✕ Reject · sync will fail",

        // === History window ===
        "history.title" => "Entry history",
        "history.snapshots" => "Snapshots",
        "history.empty" => "(no snapshots for this entry yet)",
        "history.restore_button" => "⏮ Restore this version",
        "history.restore_confirm_fmt" => "Restoring v{0} will overwrite the current entry (creates a new version, old version remains in history).",
        "history.disk_persisted" => "on disk",
        "history.in_memory" => "in memory",

        // === Recovery key ===
        "recovery.title" => "Recovery key",
        "recovery.body" => "Write down or print the following 32 groups of characters and store them offline in a safe place. Use this key to recover your vault if you forget the master password.",
        "recovery.print" => "🖨  Print",
        "recovery.save_pdf" => "📄  Save as PDF",
        "recovery.copy" => "📋  Copy",
        "recovery.saved_check" => "I have saved the recovery key offline",
        "recovery.confirm" => "Confirm and continue",
        "recovery.copied" => "✓ Copied",
        "recovery.printed" => "✓ Sent to system print dialog",
        "recovery.saved_pdf_fmt" => "✓ PDF saved to {0}",

        // === Auto-lock (v0.4) ===
        "autolock.warning_fmt" => "Auto-locking in {0} seconds (idle timeout)",
        "autolock.session_locked" => "Workstation locked — auto-locking vault",
        "autolock.system_suspend" => "System suspending — auto-locking vault",
        "autolock.cancelled" => "✓ Auto-lock cancelled",

        // === Rotation (v0.4) ===
        "rotation.title" => "One-click rotation",
        "rotation.progress_fmt" => "Rotating {0} · phase: {1}",
        "rotation.old_archived" => "✓ Old value archived to history v{0}",
        "rotation.platform_unsupported" => "This platform does not support one-click rotation. New value copied — please update manually on the platform side.",

        // === Default fallback ===
        _ => key,
    };

    public string Format(string key, params object[] args)
    {
        var template = Get(key);
        try { return string.Format(CultureInfo.InvariantCulture, template, args); }
        catch (FormatException) { return template; }
    }
}
