using System.Globalization;

namespace OmniKeyVault.Application;

/// <summary>Simplified Chinese localizer — the v0.1 / v0.2 baseline. Strings
/// match the original <c>UIStrings</c> Chinese copy verbatim so the build-time
/// XAML stays consistent. Keys not present here fall back to the key itself.</summary>
public sealed class ZhCnLocalizer : IStringLocalizer
{
    public string Locale => Locales.ZhCn;

    public string Get(string key) => key switch
    {
        // === Common ===
        "common.save" => "保存",
        "common.cancel" => "取消",
        "common.close" => "关闭",
        "common.delete" => "删除",
        "common.confirm" => "确认",
        "common.back" => "返回",
        "common.search" => "搜索",
        "common.refresh" => "刷新",
        "common.yes" => "是",
        "common.no" => "否",
        "common.ok" => "好的",
        "common.retry" => "重试",
        "common.import" => "导入",
        "common.export" => "导出",
        "common.rotate" => "轮换",
        "common.download" => "下载",
        "common.upload" => "上传",
        "common.attach" => "附件",
        "common.attachments" => "附件",

        // === Unlock window ===
        "unlock.title" => "OmniKey Vault",
        "unlock.master_password" => "主密码",
        "unlock.unlock_button" => "解锁保险库",
        "unlock.use_recovery_key" => "使用恢复密钥",
        "unlock.create_vault" => "没有金库?创建一个",
        "unlock.remember_15m" => "保持解锁 15 分钟",
        "unlock.invalid_password" => "凭据错误,请重试",
        "unlock.empty_password" => "请输入主密码",
        "unlock.deriving_key" => "派生密钥中…",
        "unlock.vault_not_found" => "未找到保险库文件",
        "unlock.last_access" => "上次访问",
        "unlock.browse" => "📂 浏览",
        "unlock.tagline" => "本地优先 · 端到端加密",
        "unlock.footer" => "无云端找回 · 零知识",

        // === Main window ===
        "main.search_watermark" => "搜索条目、字段、标签…",
        "main.list_title_all" => "全部条目",
        "main.list_title_uncategorized" => "未分类",
        "main.empty_title" => "没有匹配的条目",
        "main.empty_sub" => "试试清除筛选条件或更换搜索关键词。",
        "main.empty_vault" => "金库为空",
        "main.empty_vault_sub" => "点击 + 新建条目 开始使用",
        "main.locked" => "金库未解锁",
        "main.locked_sub" => "请运行 okv vault unlock 解锁金库",
        "main.detail_empty" => "请选择一个条目",
        "main.detail_subtitle" => "从左侧列表中选择条目以查看详情。",
        "main.folder_section" => "文件夹",
        "main.tags_section" => "标签",
        "main.new_entry" => "+ 新建条目",
        "main.import" => "↓ 导入",
        "main.export" => "↑ 导出",
        "main.sort" => "⇅ 排序",
        "main.copy_main" => "⧉  复制主字段",
        "main.copy_all" => "📋  复制全部字段(JSON)",
        "main.edit" => "✎  编辑",
        "main.duplicate" => "⧉  复制为新条目",
        "main.history" => "🕐  查看历史",
        "main.delete" => "🗑  删除",
        "main.copied" => "已复制 · 8 秒后自动清空",
        "main.clipboard_cleared" => "剪贴板已清空",
        "main.vault_unlocked_with_count" => "保险库已解锁 · 已加载 {0} 个条目",
        "main.vault_unlocked" => "保险库已解锁",
        "main.vault_locked" => "保险库已锁定 · 内存已清空",
        "main.switched_profile" => "已切换到 {0} 配置文件",
        "main.sync_synced" => "已同步 · 当前设备",
        "main.sync_manual" => "同步中…(手动触发)",
        "main.sync_complete" => "同步完成",
        "main.sync_no_change" => "已是最新,无需同步",
        "main.sync_took_remote" => "已从远端拉取更新",
        "main.sync_local_ahead" => "本地版本更新(请把本地文件复制到同步目录)",
        "main.sync_merged" => "已合并 {0} 个条目",
        "main.sync_failed" => "同步失败:",
        "main.sync_select_dir" => "选择同步目录(应包含另一个 .okv 文件,例如云盘路径)",
        "main.sync_no_okv_in_dir" => "{0} 中没有 .okv 文件",
        "main.sync_remote_change_detected" => "检测到 {0} 变化 · 点击「同步」查看最新",
        "main.remote_change_banner" => "远端有更新",
        "main.dev_tools" => "Dev Tools · v0.2",
        "main.export_seed" => "📤 导出 Seed",
        "main.import_seed" => "📥 导入 Seed",
        "main.sync" => "🔄 同步",
        "main.never_synced" => "从未同步",
        "main.lock_countdown_fmt" => "已解锁 · 剩余 {0} 分钟",
        "main.profile_banner_dev" => "DEV — 非生产数据",
        "main.profile_banner_test" => "TEST — 测试数据",
        "main.import_kdbx" => "🔐 导入 KeePass",
        "main.import_bitwarden" => "📥 导入 Bitwarden",
        "main.search_advanced" => "🔍 高级搜索",
        "main.search_hint" => "支持 tags:dev / platform:openai / field:api_key:sk-* 等语法",

        // === Editor ===
        "editor.title_new" => "新建条目",
        "editor.title_edit" => "编辑条目",
        "editor.name" => "名称",
        "editor.name_hint" => "例:OpenAI 生产环境",
        "editor.template" => "平台(模板)",
        "editor.platform_id" => "平台 ID (独立)",
        "editor.platform_id_hint" => "如:openai / github (可独立于模板)",
        "editor.type" => "类型",
        "editor.folder" => "文件夹",
        "editor.expires" => "到期 (可选)",
        "editor.tags" => "标签(逗号分隔)",
        "editor.tags_hint" => "ai, work, prod",
        "editor.fields" => "字段",
        "editor.add_totp" => "🔐 添加 TOTP",
        "editor.add_file_ref" => "📎 添加附件",
        "editor.add_field" => "+ 添加字段",
        "editor.field_key_hint" => "字段名",
        "editor.field_value_hint" => "值",
        "editor.notes" => "备注",
        "editor.duplicate_totp" => "已存在 totp_uri 字段",
        "editor.name_required" => "请输入条目名称",
        "editor.vault_locked" => "金库未解锁",
        "editor.save_failed" => "保存失败:",
        "editor.rotate" => "🔄 轮换密钥",
        "editor.rotate_title" => "轮换密钥",
        "editor.rotate_confirm" => "确认轮换 {0} 的 {1}? 旧值将归档到历史快照。",
        "editor.rotate_success" => "✓ 已轮换 {0}",
        "editor.rotate_failed" => "✕ 轮换失败:",
        "editor.rotate_unsupported" => "此条目的平台暂不支持一键轮换",
        "editor.rotate_in_progress" => "正在调用平台 API…",

        // === Settings ===
        "settings.title" => "设置",
        "settings.general" => "通用",
        "settings.security" => "安全",
        "settings.sync" => "同步 (S4-T1)",
        "settings.profiles" => "Profiles",
        "settings.devices" => "设备",
        "settings.danger" => "危险操作",
        "settings.about" => "关于",
        "settings.language" => "语言",
        "settings.theme" => "主题",
        "settings.theme_system" => "跟随系统",
        "settings.theme_dark" => "深色",
        "settings.theme_light" => "浅色",
        "settings.auto_lock" => "自动锁定(空闲)",
        "settings.clipboard" => "剪贴板自动清空",
        "settings.lock_on_session" => "系统锁屏时立即锁定",
        "settings.lock_on_suspend" => "系统休眠时立即锁定",
        "settings.idle_minutes" => "空闲超时(分钟)",
        "settings.sync_dir" => "同步目录",
        "settings.sync_dir_hint" => "(留空则监听 vault 所在目录)",
        "settings.watcher_enabled" => "启用文件监听(检测到 .okv 变化时自动提示)",
        "settings.change_password" => "修改主密码",
        "settings.view_recovery" => "查看恢复密钥",
        "settings.view_recovery_hint" => "查看恢复密钥:请使用 CLI: okv vault info",
        "settings.language_changed" => "✓ 语言已切换为 {0}",
        "settings.theme_changed" => "✓ 主题已切换为 {0}(重启窗口后生效)",
        "settings.watcher_changed" => "✓ 文件监听已{0} · 下次解锁时生效",
        "settings.sync_dir_set" => "✓ 同步目录已设置",
        "settings.device_revoked" => "✓ 已吊销设备 {0}",
        "settings.device_revoke_failed" => "✕ 吊销失败:",
        "settings.attachment_dir" => "附件存储目录",
        "settings.attachment_dir_hint" => "(留空使用默认 %APPDATA%/OmniKeyVault/attachments/)",

        // === Profile switcher ===
        "profile.switcher_title" => "切换配置文件",
        "profile.new" => "+ 新建配置文件",
        "profile.delete_confirm" => "Profile \"{0}\" 包含 {1} 个条目。确认删除?",
        "profile.delete_failed" => "删除失败:",
        "profile.create_failed" => "创建失败:",
        "profile.name_required" => "名称必须 1-32 字符",
        "profile.name_exists" => "已存在 Profile \"{0}\"",
        "profile.name_hint" => "例如:staging / sandbox / team-a",
        "profile.color" => "颜色",
        "profile.create" => "创建",
        "profile.local_only" => "仅本地",
        "profile.synced" => "已同步",
        "profile.count_fmt" => "{0} 个条目",

        // === Seed export/import ===
        "seed.export_title" => "导出 Seed (.okv.dev)",
        "seed.export_hint" => "Seed 文件未受主密码保护,仅包含 profile metadata + 字段结构,适合团队 / 跨设备 schema 同步。Secret 字段可被剥离。",
        "seed.export_profile" => "Profile",
        "seed.export_path" => "导出路径",
        "seed.export_default" => "📂 默认位置",
        "seed.export_strip" => "剥离 Secret 字段(推荐 · 共享安全)",
        "seed.export_strip_hint" => "✓ Strip 模式:导出的 seed 不含任何 Secret 字段,适合团队共享 schema 与非敏感字段。",
        "seed.export_full_hint" => "完整导出:包含 Secret 字段。仅用于受控环境,切勿公开分享。",
        "seed.export_button" => "导出",
        "seed.import_title" => "导入 Seed (.okv.dev)",
        "seed.import_hint" => "从 .okv.dev 文件导入条目。生产数据隔离:仅允许导入到 dev/test Profile。导入到 prod 需要输入确认短语。",
        "seed.import_path" => "Seed 文件路径",
        "seed.import_recent" => "📂 查找最新",
        "seed.import_target" => "目标 Profile",
        "seed.import_prod_confirm" => "⚠ 导入到 prod 是危险操作。输入「IMPORT TO PROD」确认:",
        "seed.import_prod_required" => "导入到 prod 必须输入「IMPORT TO PROD」确认,防止误操作污染生产数据。",
        "seed.import_button" => "导入",
        "seed.import_new_profile" => "+ 新建 profile",

        // === KeePass import (v0.3 S5-T6) ===
        "keepass.import_title" => "从 KeePass 导入",
        "keepass.import_hint" => "支持 KeePass 2.x XML 导出格式(在 KeePass 中: 文件 → 导出 → KeePass 2 XML)。",
        "keepass.import_path" => "XML 文件路径",
        "keepass.import_button" => "导入到当前 Profile",
        "keepass.import_success_fmt" => "✓ 已导入 {0} 个条目到 {1}",
        "keepass.import_failed" => "✕ KeePass 导入失败:",
        "keepass.parse_error" => "无法解析 KeePass XML。请确认是 KeePass 2.x 导出格式。",

        // === Search window (v0.3 S6-T3) ===
        "search.title" => "高级搜索",
        "search.placeholder" => "tags:dev AND platform:openai",
        "search.syntax_help" => "支持 tags: / platform: / field:KEY:VALUE / expired / 普通文本 · 用 AND / OR 组合",
        "search.results_fmt" => "{0} 个匹配",
        "search.no_results" => "没有匹配条目",
        "search.clear" => "清空",
        "search.field_highlighted" => "命中字段",

        // === Attachments (v0.3 S6-T5) ===
        "attachment.upload" => "📎 上传附件",
        "attachment.download" => "⬇ 下载",
        "attachment.replace" => "🔄 替换",
        "attachment.delete" => "🗑 删除",
        "attachment.size_fmt" => "{0} · {1}",
        "attachment.confirm_delete" => "确认删除附件 \"{0}\"?",
        "attachment.upload_failed" => "上传失败:",
        "attachment.not_found" => "附件不存在或已删除",
        "attachment.kind" => "附件",
        "attachment.uploaded" => "✓ 已上传 {0} ({1})",

        // === Sync conflict resolver ===
        "sync.conflict_title" => "⚠ 同步冲突",
        "sync.conflict_summary_fmt" => "检测到 {0} 个冲突条目(Vector Clock 无法自动合并)",
        "sync.conflict_local_vector" => "Vector Clock 状态",
        "sync.conflict_choice" => "选择解决方式:",
        "sync.conflict_keep_local" => "💾 保留本地",
        "sync.conflict_keep_local_sub" => "用本地版本覆盖远端。远端其他设备的修改会丢失。",
        "sync.conflict_take_remote" => "📥 采用远端",
        "sync.conflict_take_remote_sub" => "用远端版本覆盖本地。本地修改会丢失。",
        "sync.conflict_merge" => "🔀 自动合并",
        "sync.conflict_merge_sub" => "合并非冲突条目;冲突的字段需要后续手动处理。",
        "sync.conflict_cancel" => "取消",
        "sync.conflict_local_kept" => "已保留本地版本(默认 local-wins)",

        // === Device trust ===
        "trust.title" => "🔐 信任新设备",
        "trust.body" => "检测到来自未识别设备的签名。设备使用 Ed25519 公钥签名 vault 文件。一旦信任,所有该设备的未来签名都会自动通过验证。",
        "trust.device_id" => "设备 ID",
        "trust.public_key" => "公钥指纹",
        "trust.reason" => "触发原因",
        "trust.choice" => "选择:",
        "trust.trust" => "✓ 信任并记住此设备",
        "trust.trust_once" => "✓ 仅本次信任(不持久化)",
        "trust.reject" => "✕ 拒绝 · 同步将失败",

        // === History window ===
        "history.title" => "条目历史",
        "history.snapshots" => "历史快照",
        "history.empty" => "(此条目暂无历史快照)",
        "history.restore_button" => "⏮ 还原到此版本",
        "history.restore_confirm_fmt" => "还原 v{0} 会覆盖当前条目(创建新版本,旧版本可在历史中恢复)。",
        "history.disk_persisted" => "已落盘",
        "history.in_memory" => "内存中",

        // === Recovery key ===
        "recovery.title" => "恢复密钥",
        "recovery.body" => "请将以下 32 组字符抄写或打印后离线保存在安全处;凭此密钥可在忘记主密码时恢复金库。",
        "recovery.print" => "🖨  打印",
        "recovery.save_pdf" => "📄  另存为 PDF",
        "recovery.copy" => "📋  复制",
        "recovery.saved_check" => "我已离线保存恢复密钥",
        "recovery.confirm" => "确认并继续",
        "recovery.copied" => "✓ 已复制",
        "recovery.printed" => "✓ 已发送至系统打印对话框",
        "recovery.saved_pdf_fmt" => "✓ PDF 已保存到 {0}",

        // === Auto-lock (v0.4) ===
        "autolock.warning_fmt" => "{0} 秒后自动锁定(空闲超时)",
        "autolock.session_locked" => "系统已锁屏 — 自动锁定",
        "autolock.system_suspend" => "系统进入休眠 — 自动锁定",
        "autolock.cancelled" => "✓ 已取消自动锁定",

        // === Rotation (v0.4) ===
        "rotation.title" => "一键轮换",
        "rotation.progress_fmt" => "正在轮换 {0} · 阶段: {1}",
        "rotation.old_archived" => "✓ 旧值已归档到历史快照 v{0}",
        "rotation.platform_unsupported" => "此平台暂不支持一键轮换。已复制新值,请手动更新平台侧。",

        // === Default fallback ===
        _ => key,
    };

    public string Format(string key, params object[] args)
    {
        var template = Get(key);
        try { return string.Format(CultureInfo.InvariantCulture, template, args); }
        catch (FormatException) { return template; }
    }
}
